version: '3.8'

services:
  bot:
    build: .
    container_name: instacroler-bot
    restart: unless-stopped
    volumes:
      - instacroler_data:/app/data

volumes:
  instacroler_data:
    name: instacroler_data
